site:
  name: "AcquireLift |  Google Ad Grant Specialist"
  description: "Certified Google Partner helping nonprofits audit, optimize, and manage their $10,000/month Google Ad Grant. Free account audits delivered in 24-48 hours."
  site: 'https://acquirelift.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: nONFxKRdRaybTXoRwksliA4RE_YvG92hpB5erF5QzEU

# Default SEO metadata
metadata:
  title:
    default: 'AcquireLift | Google Ad Grant Specialist'
    template: '%s — AcquireLift'
  description: 'Certified Google Partner helping nonprofits audit, optimize, and manage their $10,000/month Google Ad Grant. Free account audits delivered in 24-72 hours.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: AcquireLift
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@arthelokyo'
    site: '@arthelokyo'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: G-8XWMPHFHGK 
ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
